@echo off
echo Running tests with pytest...
pytest --alluredir=allure-results
echo Generating Allure report...
allure generate allure-results -o allure-report --clean
echo Opening Allure report...
allure open allure-report
